import { EmbedItem, GalleryItem, MusicReleaseItem, SocialLink } from '../models';
import { localized } from './content-utils';

export const embedsData: readonly EmbedItem[] = [
  {
    id: 'spotify-top-tracks',
    platform: 'spotify',
    title: localized('Top tracks', 'Top tracks'),
    description: localized("Spotify's top tracks.", 'Top tracks de Spotify.'),
    url: 'https://open.spotify.com/artist/0lbM6GWkHSqGxStr0vdAwL',
    embedUrl: 'https://open.spotify.com/embed/artist/0lbM6GWkHSqGxStr0vdAwL',
  },
  {
    id: 'youtube-live-set',
    platform: 'youtube',
    title: localized('GABO MARTIN b2b JESUAN M live at NYE 2026', 'GABO MARTIN b2b JESUAN M live at NYE 2026'),
    description: localized(
      'CROSSING SOUTH X PARADOR NAUTICO',
      'CROSSING SOUTH X PARADOR NAUTICO'
    ),
    url: 'https://www.youtube.com/watch?v=R652c982s74',
    embedUrl: 'https://www.youtube.com/embed/R652c982s74',
  },
  {
    id: 'soundcloud-dj-sets',
    platform: 'soundcloud',
    title: localized('SoundCloud sets', 'Sets en SoundCloud'),
    description: localized(
      'DJ sets playlist.',
      'Playlist de DJ sets.'
    ),
    url: 'https://soundcloud.com/gabo-martin/sets/sets',
    embedUrl: 'https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/gabo-martin/sets/sets&color=%23f57634&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false',
  },
] as const;

export const musicReleaseData: readonly MusicReleaseItem[] = [
  {
    id: 'underworld',
    title: localized('Underworld', 'Underworld'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2026-03-20',
    href: 'https://www.beatport.com/release/underworld/6006701',
    embedUrl: 'https://embed.beatport.com/?id=6006701&type=release',
  },
  {
    id: 'portal-echoes',
    title: localized('Portal Echoes', 'Portal Echoes'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2026-02-12',
    href: 'https://www.beatport.com/release/portal-echoes/5830427',
    embedUrl: 'https://embed.beatport.com/?id=5830427&type=release',
  },
  {
    id: 'lying-clouds',
    title: localized('Lying Clouds', 'Lying Clouds'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2025-12-11',
    href: 'https://www.beatport.com/release/lying-clouds/5505021',
    embedUrl: 'https://embed.beatport.com/?id=5505021&type=release',
  },
  {
    id: 'boreas',
    title: localized('Boreas', 'Boreas'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2025-06-13',
    href: 'https://www.beatport.com/release/boreas/5105692',
    embedUrl: 'https://embed.beatport.com/?id=5105692&type=release',
  },
  {
    id: 'mirage-remixed',
    title: localized('Mirage (Remixed)', 'Mirage (Remixed)'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2022-10-21',
    href: 'https://www.beatport.com/release/mirage-remixed/3888838',
    embedUrl: 'https://embed.beatport.com/?id=3888838&type=release',
  },
  {
    id: 'austral',
    title: localized('Austral', 'Austral'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2022-08-19',
    href: 'https://www.beatport.com/release/austral/3807694',
    embedUrl: 'https://embed.beatport.com/?id=3807694&type=release',
  },
  {
    id: 'retreating',
    title: localized('Retreating', 'Retreating'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2022-03-07',
    href: 'https://www.beatport.com/release/retreating/3659705',
    embedUrl: 'https://embed.beatport.com/?id=3659705&type=release',
  },
  {
    id: 'unforeseen',
    title: localized('Unforeseen', 'Unforeseen'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2022-02-18',
    href: 'https://www.beatport.com/release/unforeseen/3616657',
    embedUrl: 'https://embed.beatport.com/?id=3616657&type=release',
  },
  {
    id: 'junos-desire',
    title: localized("Juno's Desire", "Juno's Desire"),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2021-12-10',
    href: 'https://www.beatport.com/release/junos-desire/3569821',
    embedUrl: 'https://embed.beatport.com/?id=3569821&type=release',
  },
  {
    id: 'oxymoron',
    title: localized('Oxymoron', 'Oxymoron'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2021-09-03',
    href: 'https://www.beatport.com/release/oxymoron/3465542',
    embedUrl: 'https://embed.beatport.com/?id=3465542&type=release',
  },
  {
    id: 'mirage',
    title: localized('Mirage', 'Mirage'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2021-02-01',
    href: 'https://www.beatport.com/release/mirage/3237466',
    embedUrl: 'https://embed.beatport.com/?id=3237466&type=release',
  },
  {
    id: 'parana',
    title: localized('Parana', 'Parana'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2020-12-25',
    href: 'https://www.beatport.com/release/parana/3161445',
    embedUrl: 'https://embed.beatport.com/?id=3161445&type=release',
  },
  {
    id: 'mindstate',
    title: localized('Mindstate', 'Mindstate'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2020-08-10',
    href: 'https://www.beatport.com/release/mindstate/3043342',
    embedUrl: 'https://embed.beatport.com/?id=3043342&type=release',
  },
  {
    id: 'parallel-cities',
    title: localized('Parallel Cities', 'Parallel Cities'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2019-06-03',
    href: 'https://www.beatport.com/release/parallel-cities/2506785',
    embedUrl: 'https://embed.beatport.com/?id=2506785&type=release',
  },
  {
    id: 'altair',
    title: localized('Altair', 'Altair'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2018-12-10',
    href: 'https://www.beatport.com/release/altair/2328448',
    embedUrl: 'https://embed.beatport.com/?id=2328448&type=release',
  },
  {
    id: 'renaissance',
    title: localized('Renaissance', 'Renaissance'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Release', 'Lanzamiento'),
    releaseDate: '2018-08-13',
    href: 'https://www.beatport.com/release/renaissance/2242413',
    embedUrl: 'https://embed.beatport.com/?id=2242413&type=release',
  },
] as const;

export const musicRemixesData: readonly MusicReleaseItem[] = [
  {
    id: 'starlines-remix',
    title: localized('Starlines - Gabo Martin Remix', 'Starlines - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2026-01-09',
    href: 'https://www.beatport.com/track/starlines/23102180',
    embedUrl: 'https://embed.beatport.com/?id=23102180&type=track',
  },
  {
    id: 'strange-wonders-remix',
    title: localized('Strange Wonders - Gabo Martin Remix', 'Strange Wonders - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2025-08-08',
    href: 'https://www.beatport.com/track/strange-wonders/20636472',
    embedUrl: 'https://embed.beatport.com/?id=20636472&type=track',
  },
  {
    id: 'night-vibrations-remix',
    title: localized('Night Vibrations - Gabo Martin Remix', 'Night Vibrations - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2024-08-28',
    href: 'https://www.beatport.com/track/night-vibrations/19354509',
    embedUrl: 'https://embed.beatport.com/?id=19354509&type=track',
  },
  {
    id: 'devoto-remix',
    title: localized('Devoto - Gabo Martin Remix', 'Devoto - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2024-06-14',
    href: 'https://www.beatport.com/track/devoto/19101692',
    embedUrl: 'https://embed.beatport.com/?id=19101692&type=track',
  },
  {
    id: 'catalyst-remix',
    title: localized('Catalyst - Gabo Martin Remix', 'Catalyst - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2023-09-08',
    href: 'https://www.beatport.com/track/catalyst/18066496',
    embedUrl: 'https://embed.beatport.com/?id=18066496&type=track',
  },
  {
    id: 'destino-remix',
    title: localized('Destino - Gabo Martin Remix', 'Destino - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2023-07-07',
    href: 'https://www.beatport.com/track/destino/17714900',
    embedUrl: 'https://embed.beatport.com/?id=17714900&type=track',
  },
  {
    id: 'sombra-remix',
    title: localized('Sombra - Gabo Martin Remix', 'Sombra - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2023-05-26',
    href: 'https://www.beatport.com/track/sombra/17684956',
    embedUrl: 'https://embed.beatport.com/?id=17684956&type=track',
  },
  {
    id: 'big-bang-remix',
    title: localized('Big Bang - Gabo Martin Remix', 'Big Bang - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2023-02-10',
    href: 'https://www.beatport.com/track/big-bang/17321837',
    embedUrl: 'https://embed.beatport.com/?id=17321837&type=track',
  },
  {
    id: 'cygnus-remix',
    title: localized('Cygnus - Gabo Martin Remix', 'Cygnus - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2022-12-02',
    href: 'https://www.beatport.com/track/cygnus/17135800',
    embedUrl: 'https://embed.beatport.com/?id=17135800&type=track',
  },
  {
    id: 'lullaby-remix',
    title: localized('Lullaby - Gabo Martin Remix', 'Lullaby - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2022-07-25',
    href: 'https://www.beatport.com/track/lullaby/16693432',
    embedUrl: 'https://embed.beatport.com/?id=16693432&type=track',
  },
  {
    id: 'dharma-remix',
    title: localized('Dharma - Gabo Martin, Jesuan M Remix', 'Dharma - Gabo Martin, Jesuan M Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2022-03-11',
    href: 'https://www.beatport.com/track/dharma/16268966',
    embedUrl: 'https://embed.beatport.com/?id=16268966&type=track',
  },
  {
    id: 'nozomu-remix',
    title: localized('Nozomu - Gabo Martin Remix', 'Nozomu - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2022-03-04',
    href: 'https://www.beatport.com/track/nozomu/16167512',
    embedUrl: 'https://embed.beatport.com/?id=16167512&type=track',
  },
  {
    id: 'durand-remix',
    title: localized('Durand - Gabo Martin Remix', 'Durand - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2021-08-13',
    href: 'https://www.beatport.com/track/durand/15501969',
    embedUrl: 'https://embed.beatport.com/?id=15501969&type=track',
  },
  {
    id: 'holy-ground-alt-mix',
    title: localized("Holy Ground - Gabo Martin's Alt Mix", "Holy Ground - Gabo Martin's Alt Mix"),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2021-07-26',
    href: 'https://www.beatport.com/track/holy-ground/15460669',
    embedUrl: 'https://embed.beatport.com/?id=15460669&type=track',
  },
  {
    id: 'holy-ground-state-of-trance-mix',
    title: localized("Holy Ground - Gabo Martin's State of Trance Mix", "Holy Ground - Gabo Martin's State of Trance Mix"),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2021-07-26',
    href: 'https://www.beatport.com/track/holy-ground/15460671',
    embedUrl: 'https://embed.beatport.com/?id=15460671&type=track',
  },
  {
    id: 'rip-current-remix',
    title: localized('Rip Current - Gabo Martin & Jesuan M Remix', 'Rip Current - Gabo Martin & Jesuan M Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2021-05-21',
    href: 'https://www.beatport.com/track/rip-current/15240460',
    embedUrl: 'https://embed.beatport.com/?id=15240460&type=track',
  },
  {
    id: 'insomnio-remix',
    title: localized('Insomnio - Gabo Martin Remix', 'Insomnio - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2021-03-19',
    href: 'https://www.beatport.com/track/insomnio/14649858',
    embedUrl: 'https://embed.beatport.com/?id=14649858&type=track',
  },
  {
    id: 'simulation-remix',
    title: localized('Simulation - Gabo Martin Remix', 'Simulation - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2020-12-28',
    href: 'https://www.beatport.com/track/simulation/14574334',
    embedUrl: 'https://embed.beatport.com/?id=14574334&type=track',
  },
  {
    id: 'wake-up-4am-remix',
    title: localized('Wake Up - Gabo Martin 4AM Remix', 'Wake Up - Gabo Martin 4AM Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2020-12-21',
    href: 'https://www.beatport.com/track/wake-up/14662044',
    embedUrl: 'https://embed.beatport.com/?id=14662044&type=track',
  },
  {
    id: 'moais-remix',
    title: localized('Moais - Gabo Martin Rmx', 'Moais - Gabo Martin Rmx'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2020-09-28',
    href: 'https://www.beatport.com/track/moais/13408275',
    embedUrl: 'https://embed.beatport.com/?id=13408275&type=track',
  },
  {
    id: 'rising-remix',
    title: localized('Rising - Gabo Martin Remix', 'Rising - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2019-08-08',
    href: 'https://www.beatport.com/track/rising/11755331',
    embedUrl: 'https://embed.beatport.com/?id=11755331&type=track',
  },
  {
    id: 'parallel-cities-edit',
    title: localized('Parallel Cities - Gabo Martin Edit', 'Parallel Cities - Gabo Martin Edit'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2019-06-03',
    href: 'https://www.beatport.com/track/parallel-cities/11590243',
    embedUrl: 'https://embed.beatport.com/?id=11590243&type=track',
  },
  {
    id: 'glass-bridge-remix',
    title: localized('Glass Bridge - Gabo Martin Remix', 'Glass Bridge - Gabo Martin Remix'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Remix', 'Remix'),
    releaseDate: '2018-12-13',
    href: 'https://www.beatport.com/track/glass-bridge/10846674',
    embedUrl: 'https://embed.beatport.com/?id=10846674&type=track',
  },
] as const;

export const musicSinglesData: readonly MusicReleaseItem[] = [
  {
    id: 'rumble',
    title: localized('Rumble', 'Rumble'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2025-10-22',
    href: 'https://www.beatport.com/track/rumble/21996525',
    embedUrl: 'https://embed.beatport.com/?id=21996525&type=track',
  },
  {
    id: 'tsunami',
    title: localized('Tsunami', 'Tsunami'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2025-03-06',
    href: 'https://www.beatport.com/track/tsunami/20062504',
    embedUrl: 'https://embed.beatport.com/?id=20062504&type=track',
  },
  {
    id: 'influence',
    title: localized('Influence', 'Influence'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2024-03-07',
    href: 'https://www.beatport.com/track/influence/18659661',
    embedUrl: 'https://embed.beatport.com/?id=18659661&type=track',
  },
  {
    id: 'mindseeker',
    title: localized('Mindseeker', 'Mindseeker'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2023-08-18',
    href: 'https://www.beatport.com/track/mindseeker/17963133',
    embedUrl: 'https://embed.beatport.com/?id=17963133&type=track',
  },
  {
    id: 'dislocator',
    title: localized('Dislocator', 'Dislocator'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2022-10-19',
    href: 'https://www.beatport.com/track/dislocator/16952866',
    embedUrl: 'https://embed.beatport.com/?id=16952866&type=track',
  },
  {
    id: 'ashes-to-ashes',
    title: localized('Ashes to Ashes', 'Ashes to Ashes'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2021-12-16',
    href: 'https://www.beatport.com/track/ashes-to-ashes/15944389',
    embedUrl: 'https://embed.beatport.com/?id=15944389&type=track',
  },
  {
    id: 'dust-to-dust',
    title: localized('Dust to Dust', 'Dust to Dust'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2021-07-09',
    href: 'https://www.beatport.com/track/dust-to-dust/15448573',
    embedUrl: 'https://embed.beatport.com/?id=15448573&type=track',
  },
  {
    id: 'mistaken',
    title: localized('Mistaken', 'Mistaken'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2021-02-08',
    href: 'https://www.beatport.com/track/mistaken/14836503',
    embedUrl: 'https://embed.beatport.com/?id=14836503&type=track',
  },
  {
    id: 'not-enough',
    title: localized('Not Enough', 'Not Enough'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2021-01-25',
    href: 'https://www.beatport.com/track/not-enough/14786729',
    embedUrl: 'https://embed.beatport.com/?id=14786729&type=track',
  },
  {
    id: 'only-you',
    title: localized('Only You', 'Only You'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2020-10-19',
    href: 'https://www.beatport.com/track/only-you/14264605',
    embedUrl: 'https://embed.beatport.com/?id=14264605&type=track',
  },
  {
    id: 'a-ticket-to-mars',
    title: localized('A Ticket to Mars', 'A Ticket to Mars'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2020-06-22',
    href: 'https://www.beatport.com/track/a-ticket-to-mars/13578626',
    embedUrl: 'https://embed.beatport.com/?id=13578626&type=track',
  },
  {
    id: 'sur',
    title: localized('Sur', 'Sur'),
    artists: localized('Gabo Martin', 'Gabo Martin'),
    label: localized('Single', 'Single'),
    releaseDate: '2018-09-17',
    href: 'https://www.beatport.com/track/sur/10603201',
    embedUrl: 'https://embed.beatport.com/?id=10603201&type=track',
  },
] as const;

export const galleryData: readonly GalleryItem[] = [
  {
    id: 'gallery-club-room',
    type: 'image',
    title: localized('Club room', 'Sala de club'),
    alt: localized('Gabo Martin performing in a club room.', 'Gabo Martin tocando en una sala de club.'),
    src: '/images/placeholders/gallery-club-room.svg',
  },
  {
    id: 'gallery-booth',
    type: 'image',
    title: localized('Booth', 'Cabina'),
    alt: localized('DJ booth placeholder with stage lights.', 'Placeholder de cabina con luces de escenario.'),
    src: '/images/placeholders/gallery-booth.svg',
  },
  {
    id: 'gallery-crowd',
    type: 'image',
    title: localized('Crowd', 'Pista'),
    alt: localized('Crowd placeholder with stage lighting.', 'Placeholder de pista con luces de escenario.'),
    src: '/images/placeholders/gallery-crowd.svg',
  },
  {
    id: 'gallery-studio-detail',
    type: 'image',
    title: localized('Studio detail', 'Detalle de estudio'),
    alt: localized('Studio setup prepared for music selection.', 'Setup de estudio preparado para selección musical.'),
    src: '/images/placeholders/gallery-studio-detail.svg',
  },
  {
    id: 'gallery-studio-wide',
    type: 'image',
    title: localized('Studio', 'Estudio'),
    alt: localized('Wide studio setup placeholder.', 'Placeholder de setup de estudio amplio.'),
    src: '/images/placeholders/gallery-studio-wide.svg',
  },
  {
    id: 'gallery-live-recap',
    type: 'image',
    title: localized('Live recap', 'Resumen en vivo'),
    alt: localized('Live recap placeholder.', 'Placeholder de resumen en vivo.'),
    src: '/images/placeholders/gallery-live-recap.svg',
  },
] as const;

export const socialLinksData: readonly SocialLink[] = [
  { id: 'instagram', platform: 'instagram', label: localized('Instagram', 'Instagram'), url: 'https://www.instagram.com/gabo.martin/', handle: '@gabo.martin' },
  { id: 'spotify', platform: 'spotify', label: localized('Spotify', 'Spotify'), url: 'https://open.spotify.com/artist/0lbM6GWkHSqGxStr0vdAwL', handle: 'Gabo Martin' },
  { id: 'youtube', platform: 'youtube', label: localized('YouTube', 'YouTube'), url: 'https://youtube.com/@gabomartinmusic', handle: '@gabomartinmusic' },
  { id: 'soundcloud', platform: 'soundcloud', label: localized('SoundCloud', 'SoundCloud'), url: 'https://soundcloud.com/gabo-martin', handle: 'soundcloud.com/gabo-martin' },
  { id: 'email', platform: 'email', label: localized('Email', 'Correo'), url: 'mailto:contact@gabomartin.com', handle: 'contact@gabomartin.com' },
] as const;

export const embedData = embedsData;
export const galleriesData = galleryData;
export const musicRemixData = musicRemixesData;
export const musicSingleData = musicSinglesData;
export const socialLinkData = socialLinksData;
